version: '3'

services:
  jira:
    container_name: jira
    depends_on:
      - postgres-j
    image: atlassian/jira-software:8.5.4
    networks:
      - jiranet
    volumes:
      - jira_home:/var/atlassian/application-data/jira
    ports:
      - 8080:8080
    restart: always
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres-j:5432/jiradb
      - ATL_JDBC_USER=jiradbuser
      - ATL_JDBC_PASSWORD=admin
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      - SETENV_JVM_MINIMUM_MEMORY=10000m
      - SETENV_JVM_MAXIMUM_MEMORY=15000m
      
  postgres-j:
    container_name: pg
    image: postgres:9.6
    ports:
      - 5432:5432
    networks:
      - jiranet
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
      - POSTGRES_USER=jiradbuser
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jiradb
      
volumes:
  jira_home:
    external: false
  pg_data:
    external: false

networks:
  jiranet:
    driver: bridge
